# Generated by Django 3.2.25 on 2026-01-03 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('processing', 'قيد المعالجة'), ('shipped', 'تم الشحن'), ('delivered', 'تم التوصيل'), ('completed', 'مكتمل'), ('cancelled', 'ملغي')], default='pending', max_length=20),
        ),
    ]
