# Generated by Django 5.2.7 on 2026-01-13 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='imagae',
            new_name='image',
        ),
    ]
